site_name: Bioinformática aplicada a la genómica bacteriana usando Python
site_description:
site_url: https://eduardo1011.github.io/curso26/

theme:
  name: material
  language: es
  logo: assets/Imagen3.png
  favicon: assets/Imagen3.png

  palette:
    scheme: default
    primary: custom
    accent: custom

  features:
    # Navegación
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.footer
    # Índice
    - toc.follow
    # Buscador
    - search.suggest
    - search.highlight
    - search.share
    # Código
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # Contenido
    - content.tabs.link
    - content.tooltips

plugins:
  - search:
      lang: es

nav:
  - Programa del curso: index.md
  - Sesión 1: sesion1.md
  - Sesión 2: sesion2.md
  - Sesión 3: sesion3.md
  - Sesión 4: sesion4.md
  - Sesión 5: sesion5.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

copyright: Curso de Bioinformática · Septiembre · 2026
