name: Publicar sitio MkDocs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar MkDocs
        run: pip install -r requirements.txt

      - name: Construir sitio
        run: mkdocs build --strict

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Subir sitio generado
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Publicar
        uses: actions/deploy-pages@v4
        id: deployment

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
